---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 100
num_rounds: 200
verbose: 1

dataset:
  name: 'mnist' # [cifar10, mnist]
  # If path is specified, look for (or download) the dataset in that path,
  # otherwise use current folder.
  data_path: './dataset'
  split: 'iid' # {iid, non-iid}
  classes_pc: 4
  minibatch_size: 128

model:
  name: 'Conv4' # [Conv8/6/4, LeNet]
  mode: 'mask' # [mask, dense]
  local_epochs: 3
  activation: 'relu'
  agg_steps: 5

strategy:
  _target_: fedpm.strategy.DenseStrategy
  _recursive_: false
  fraction_fit: 0.02
  fraction_evaluate: 0
  min_fit_clients: 0
  min_evaluate_clients: 0
  min_available_clients: 0
  compressor_cfg: ${compressor}
  device: cpu
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  
client:
  _target_: fedpm.client.DenseClient
  _recursive_: false
  model_cfg: ${model}
  compressor_cfg: ${compressor}
  

compressor:
  compress: True
  # _recursive_: false
  type: 'sign_sgd' # {sign_sgd, qsgd}
  local_epochs: 3
  sign_sgd:
    _target_: fedpm.compressors.sign_sgd.SignSGDCompressor
    local_lr: 0.1
    server_lr: 0.0002
  qsgd:
    _target_: fedpm.compressors.qsgd.QSGDCompressor
    local_lr: 0.0003
    server_lr: 0.1
    num_level: 6
  fedavg:
    local_lr: 0.01
    server_lr: 0.0002


client_resources:
  num_cpus: 6
  num_gpus: 0
